var mycanvas = document.getElementById('canvas');
var ctx = mycanvas.getContext('2d');
var snakeSize = 15; 
var w = 750;
var h = 750;
var score = 0;
var snake;
var hwallvisit = false;
var vwallvisit = false;
var food;
var wall_arrayh = [];
var paint;
var p = false;
var gamePaused;
var wall_arrayv = [];
var toscore;
var foodtype = 20;
var visited = false;
var pfoodtype;